# -*- coding: utf-8 -*-
"""L2N_V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvZyV3qpurTOca2NMbs7EuPXUsBhKMlm

## Lecture-to-Notes (L2N): Multimodal Automated Note Generation

### Problem Statement
Lectures, academic talks, and classroom presentations remain a primary mode of knowledge delivery in modern education. However, students often struggle to capture complete, accurate, and well-structured notes during live sessions due to the fast pace of explanations, complexity of concepts, and the multimodal nature of teaching materials (spoken explanations, slides, annotations, etc.). Raw transcripts from lecture recordings or digitized slides are typically long, unorganized, and noisy, making them difficult to use directly for studying. Existing transcription and summarization tools usually rely on a single input type (e.g., only audio or only text) and therefore fail to capture the full context of a lecture. This creates a strong need for automated systems that can convert unstructured lecture material into concise, high-quality, human-readable notes.

### Proposed System
This notebook implements a hybrid, multimodal pipeline that integrates:
- **OCR** for extracting text from PDF slide images.
- **ASR (Automatic Speech Recognition)** for transcribing lecture audio/video.
- **Slide parsing** for reading text content from PPTX files.
- **Advanced text preprocessing** to clean and normalize raw transcripts.
- **LLM-based summarization** (extractive + abstractive) to generate structured, topic-wise lecture notes.

The system supports multiple input formats (audio/video, PDF slides, PPTX slides), unifies them into a single cleaned transcript, and then produces structured outputs (JSON + Markdown) organized as TL;DR, key takeaways, and detailed topic-wise notes.

### Aim
This work aims to build a robust, multimodal, and user-centric system that transforms raw educational inputs into organized, human-readable, and potentially handwritten-style outputs. The ultimate goal is to enhance learning efficiency, reduce cognitive load during note-taking, and support diverse study preferences by automatically generating high-quality lecture notes from real-world teaching materials.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install openai-whisper python-pptx pdf2image pytesseract sentence-transformers nltk torch

import whisper
import pytesseract
from pdf2image import convert_from_path
from pptx import Presentation
import os
try:
    from google.colab import files
    COLAB_ENV = True
except ImportError:
    files = None
    COLAB_ENV = False

if 'files' in globals() and files is not None:
    uploaded = files.upload()
    file_name = list(uploaded.keys())[0]
else:
    file_name = input("Enter the path to your input file (audio/video/PDF/PPTX): ").strip()

print("\n Uploaded:", file_name)

model = whisper.load_model("base")


def extract_from_video_audio(file_name):
    print("\n Processing Audio/Video...")
    result = model.transcribe(file_name)
    transcript = result["text"]

    print("\n TRANSCRIPT OUTPUT:\n")
    print(transcript)

    with open("transcript_output.txt", "w") as f:
        f.write(transcript)

def extract_from_pdf(file_name):
    print("\n Processing PDF slides...")

    # Install poppler-utils if not already installed (required by pdf2image)
    os.system("apt-get install -y poppler-utils")

    pages = convert_from_path(file_name)
    slide_number = 1
    all_text = []

    for page in pages:
        text = pytesseract.image_to_string(page)
        print(f"\n SLIDE {slide_number}\n{text}\n")
        all_text.append(f"SLIDE {slide_number}\n{text}\n")
        slide_number += 1

    # Save everything into transcript_output.txt so the next cell can read it
    with open("transcript_output.txt", "w") as f:
        f.write("\n".join(all_text))

    print("\nSaved combined text to transcript_output.txt")


def extract_from_ppt(file_name):
    print("\n Processing PPT slides...")

    prs = Presentation(file_name)
    slide_number = 1
    all_text = []

    for slide in prs.slides:
        text = []
        for shape in slide.shapes:
            if hasattr(shape, "text") and shape.text:
                text.append(shape.text)

        slide_text = "\n".join(text)
        print(f"\n SLIDE {slide_number}\n")
        print(slide_text)
        all_text.append(f"SLIDE {slide_number}\n{slide_text}\n")
        slide_number += 1

    # Save everything into transcript_output.txt so the next cell can read it
    with open("transcript_output.txt", "w") as f:
        f.write("\n".join(all_text))

    print("\nSaved combined text to transcript_output.txt from PPT slides")


file_ext = file_name.lower().split(".")[-1]

if file_ext in ["mp4", "mp3", "wav", "m4a"]:
    extract_from_video_audio(file_name)

elif file_ext == "pdf":
    extract_from_pdf(file_name)

elif file_ext == "pptx":
    extract_from_ppt(file_name)

else:
    print("Unsupported file type")

import re

with open("transcript_output.txt", "r") as f:
    text = f.read()

formatted = text.strip()
formatted = re.sub(r'\s+', ' ', formatted)
formatted = re.sub(r'(\.)([A-Za-z])', r'.\n\2', formatted)
formatted = formatted.replace("&", "and")
formatted = re.sub(r'\b(\w+)( \1\b)+', r'\1', formatted)

print("\nFORMATTED TRANSCRIPT:\n")
print(formatted)

with open("cleaned_transcript.txt", "w") as f:
    f.write(formatted)

"""
lecture_to_notes.py
Reads cleaned_transcript.txt -> produces structured notes (JSON + markdown).
Requires: transformers, sentence_transformers, nltk, torch
"""

import os
import json
import math
from typing import List, Dict

import torch
from transformers import pipeline
from sentence_transformers import SentenceTransformer, util
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")
from nltk.tokenize import sent_tokenize

INPUT_TRANSCRIPT = "cleaned_transcript.txt"
OUTPUT_JSON = "lecture_notes.json"
OUTPUT_MD = "lecture_notes.md"

# Config
CHUNK_WORD_TARGET = 450
EXTRACTIVE_SENTENCES_PER_CHUNK = 6
SUMMARIZER_MODEL = "facebook/bart-large-cnn"
DEVICE = 0 if torch.cuda.is_available() else -1

# Utilities
def read_transcript(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read().strip()

def split_into_sentences(text: str) -> List[str]:
    # NLTK sentence tokenizer is robust for transcripts after cleaning
    sents = sent_tokenize(text)
    return [s.strip() for s in sents if s.strip()]

def chunk_sentences_by_wordcount(sentences: List[str], target_words: int) -> List[List[str]]:
    chunks = []
    current = []
    current_words = 0
    for s in sentences:
        wcount = len(s.split())
        if current and current_words + wcount > target_words:
            chunks.append(current)
            current = []
            current_words = 0
        current.append(s)
        current_words += wcount
    if current:
        chunks.append(current)
    return chunks

# Extractive selection
def extract_top_sentences(sentences: List[str], model: SentenceTransformer, k: int) -> List[str]:
    """
    Scores sentences by closeness to the chunk centroid embedding, returns top-k unique sentences
    """
    if not sentences:
        return []
    embeddings = model.encode(sentences, convert_to_tensor=True, show_progress_bar=False)
    centroid = embeddings.mean(dim=0)
    scores = util.cos_sim(embeddings, centroid).cpu().numpy().squeeze()
    idx_sorted = scores.argsort()[::-1]
    top_idx = idx_sorted[:min(k, len(sentences))]
    # Keep original order for readability
    top_idx_sorted = sorted(top_idx)
    return [sentences[i] for i in top_idx_sorted]

# Abstractive summarization wrapper
def summarize_chunks(chunk_texts: List[str], summarizer_pipeline, max_length=150, min_length=30) -> List[str]:
    summaries = []
    for txt in chunk_texts:
        out = summarizer_pipeline(
            txt,
            max_length=max_length,
            min_length=min_length,
            do_sample=False,
            truncation=True
        )
        if isinstance(out, list) and len(out) > 0 and "summary_text" in out[0]:
            summaries.append(out[0]["summary_text"].strip())
        else:
            summaries.append(out[0].get("generated_text", "").strip())
    return summaries

# Assemble notes
def make_tldr_from_summaries(summaries: List[str], summarizer_pipeline) -> str:
    # make a short TL;DR
    combined = " ".join(summaries)
    short = summarizer_pipeline(combined, max_length=200, min_length=20, do_sample=False, truncation=True)
    return short[0].get("summary_text", "").strip()

def build_key_takeaways(summaries: List[str], max_takeaways=8) -> List[str]:
    s = []
    for summ in summaries:
        sents = sent_tokenize(summ)
        for sent in sents:
            cleaned = sent.strip()
            if cleaned:
                s.append(cleaned)
    seen = set()
    result = []
    for sent in s:
        key = sent.lower()
        if key not in seen:
            result.append(sent)
            seen.add(key)
        if len(result) >= max_takeaways:
            break
    return result

# Export helpers
def notes_to_markdown(notes_json: Dict) -> str:
    md = []
    md.append(f"# {notes_json.get('title', 'Lecture Summary')}\n")
    md.append("## TL;DR\n")
    md.append(notes_json.get("tldr", "") + "\n")
    md.append("## Key Takeaways\n")
    for k in notes_json.get("key_takeaways", []):
        md.append(f"- {k}")
    md.append("\n## Detailed Notes\n")
    for i, topic in enumerate(notes_json.get("detailed_notes", []), 1):
        heading = topic.get("heading", f"Topic {i}")
        md.append(f"### {heading}")
        for b in topic.get("bullets", []):
            md.append(f"- {b}")
    # Formulas and definitions extracted from the transcript
    if notes_json.get("formulas") or notes_json.get("definitions"):
        md.append("\n## Formulas / Definitions\n")
        for f in notes_json.get("formulas", []):
            md.append(f"- {f}")
        for d in notes_json.get("definitions", []):
            md.append(f"- {d}")
    if notes_json.get("examples"):
        md.append("\n## Examples\n")
        for ex in notes_json.get("examples", []):
            md.append(f"- {ex}")
    if notes_json.get("action_items"):
        md.append("\n## Action Items / Follow-ups\n")
        for it in notes_json.get("action_items", []):
            md.append(f"- {it}")
    return "\n".join(md)

# Main pipeline
def lecture_to_notes_pipeline(input_path: str):
    raw = read_transcript(input_path)
    sentences = split_into_sentences(raw)
    if not sentences:
        raise ValueError("No sentences found in transcript. Check input file.")
    chunks = chunk_sentences_by_wordcount(sentences, CHUNK_WORD_TARGET)

    # Load models
    print("Loading extractive model (sentence-transformers)...")
    sbert = SentenceTransformer("all-MiniLM-L6-v2")  # small + fast
    print("Loading summarizer model...")
    summarizer = pipeline("text-generation", model=SUMMARIZER_MODEL, device=DEVICE)

    chunk_texts_for_abstractive = []
    chunk_topics = []

    for i, chunk_sents in enumerate(chunks):
        print(f"Processing chunk {i+1}/{len(chunks)} (sentences={len(chunk_sents)})...")
        # 1) Extractive selection
        top_sents = extract_top_sentences(chunk_sents, sbert, EXTRACTIVE_SENTENCES_PER_CHUNK)
        # 2) Prepare chunk text for abstractive summarizer (concatenate top sentences)
        chunk_text = " ".join(top_sents)
        # Fallback: if too short, just use the full chunk
        if len(chunk_text.split()) < 30:
            chunk_text = " ".join(chunk_sents)
        chunk_texts_for_abstractive.append(chunk_text)
        # For headings, we can use the first top sentence (or heuristic)
        if top_sents:
            heading = top_sents[0][:80]  # short preview as heading
        else:
            heading = "Topic {}".format(i+1)
        chunk_topics.append({"heading": heading, "source_sentences": top_sents})

    # 3) Abstractive summarization per chunk
    print("Running abstractive summarizer on chunks...")
    chunk_summaries = summarize_chunks(chunk_texts_for_abstractive, summarizer)

    # 4) Build final structured notes
    print("Assembling final notes...")
    title = sentences[0][:80] if sentences else "Lecture Summary"
    tldr = make_tldr_from_summaries(chunk_summaries, summarizer)
    key_takeaways = build_key_takeaways(chunk_summaries, max_takeaways=8)

    detailed_notes = []
    for topic, summary in zip(chunk_topics, chunk_summaries):
        # split summary into bullet-like sentences
        bullets = [s.strip() for s in sent_tokenize(summary)]
        detailed_notes.append({
            "heading": topic["heading"],
            "bullets": bullets,
            "source_sentences": topic["source_sentences"]
        })

    all_text = " ".join(chunk_texts_for_abstractive)
    definitions = [s for s in sentences if any(kw in s.lower() for kw in ["is defined as", "is called", "refers to", "means"])]
    examples = [s for s in sentences if any(kw in s.lower() for kw in ["for example", "for instance", "e.g."])]

    notes = {
        "title": title,
        "tldr": tldr,
        "key_takeaways": key_takeaways,
        "detailed_notes": detailed_notes,
        "formulas": [],
        "definitions": definitions,
        "examples": examples,
        "action_items": []
    }

    # Save outputs
    with open(OUTPUT_JSON, "w", encoding="utf-8") as fo:
        json.dump(notes, fo, indent=2, ensure_ascii=False)
    md = notes_to_markdown(notes)
    with open(OUTPUT_MD, "w", encoding="utf-8") as fo:
        fo.write(md)

    print(f"Done. JSON -> {OUTPUT_JSON}, Markdown -> {OUTPUT_MD}")
    return notes

# Commented out IPython magic to ensure Python compatibility.
# Run
# %pip install --upgrade transformers

if not os.path.exists(INPUT_TRANSCRIPT):
    raise FileNotFoundError(f"Input transcript not found: {INPUT_TRANSCRIPT}")

notes = lecture_to_notes_pipeline(INPUT_TRANSCRIPT)

print("\n--- TL;DR ---\n")
print(notes["tldr"])
print("\n--- Key takeaways ---")
for k in notes["key_takeaways"]:
    print("-", k)